chat/accounts/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [
    url(r'^$', views.login_user, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^signup/$', views.Signup, name='signup'),
    ]

chat/chat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('chating.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^profile/', include('profiles.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {"document_root": settings.MEDIA_ROOT})
]
# if settings.DEBUG:
#     urlpatterns += url('', (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

chat/accounts/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User, Group


class Chats(models.Model): #extra
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    message = models.CharField(max_length=200)

    def __unicode__(self):
        return self.message


class ExtendGroup(Group):
    chat = models.ManyToManyField(Chats, blank=True) #extra
    created = models.DateTimeField(auto_now_add=True)
    # user = models.ManyToManyField(User, blank=True)

    def __unicode__(self):
        return self.name

class UserDetails(models.Model):
    # user = models.ForeignKey(User, null=True, blank=True)
    user = models.OneToOneField(User, null=True, blank=True)
    user_description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='img/', blank=True, null=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    mobile_no = models.IntegerField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    group = models.ManyToManyField(Group, blank=True)

    def __unicode__(self):
        return u'%s' % (self.user.username)

chat/accounts/forms.py
from django import forms
from .models import UserDetails
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    email = forms.EmailField(max_length=75, widget=forms.TextInput(attrs={'class': 'form-control','required': 'required' }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'required': 'required'}))

    def clean_email(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        # current_user = self.instance.email
        if not User.objects.filter(email=email):
            raise forms.ValidationError("This email does not exist !")
        return email

class SignUpForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','required':'required'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','required':'required'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'required':'required'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'required':'required'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'required':'required'}))

    def clean(self):
        cleaned_data = super(SignUpForm, self).clean()
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        # current_user = self.instance.email
        if not confirm_password == password:
        # if not User.objects.filter(email=email):
            raise forms.ValidationError("Password not match with Confirm Password !")
        return cleaned_data

    def clean_email(self):
        cleaned_data = super(SignUpForm, self).clean()
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError("This email already exist !")
        return email

# class UserDetailsForm(forms.ModelForm):
#     class Meta:
#         model = UserDetails
#         fields = ('user_description', 'image', 'state', 'city', 'mobile_no', 'address')
#         # widgets = {
#         #     'image': FileInput(),
#         # }
#
#     def __init__(self, *args, **kwargs):
#         super(UserDetails, self).__init__(*args, **kwargs)
#         self.fields['image'].widget.attrs.update({'class': 'form-control'})
#         self.fields['city'].widget.attrs.update({'class': 'form-control', 'required': 'required'})
#         self.fields['state'].widget.attrs.update({'class': 'form-control', 'required': 'required'})
#         self.fields['mobile_no'].widget.attrs.update({'class': 'form-control', 'required': 'required'})
#         self.fields['address'].widget.attrs.update({'class': 'form-control', 'cols': '100', 'rows': '5', 'required': 'required'})
#         self.fields['user_description'].widget.attrs.update({'class': 'form-control', 'cols': '100', 'rows': '5', 'required': 'required'})

    # class Meta:
    #     model = UserDetails
    #     fields = ('image', 'state', 'city', 'mobile_no', 'address', 'first_name', 'last_name', 'email', 'password', 'confirm_password')
    #     widgets = {
    #         'image': FileInput(),
    #     }
    #
    # def __init__(self, *args, **kwargs):
    # super(ProfileForm, self).__init__(*args, **kwargs)
    # self.fields['image'].widget.attrs.update({'class': 'py-form-control'})
    # self.fields['state'].widget.attrs.update({'class': 'py-form-control', 'required': 'required'})
    # self.fields['mobile_no'].widget.attrs.update({'class': 'py-form-control', 'required': 'required'})
    # self.fields['address'].widget.attrs.update({'class': 'py-form-control', 'cols': '100', 'rows': '5', 'required': 'required'})

chat/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .forms import LoginForm, SignUpForm
from .models import UserDetails
from .utils import create_username

def login_user(request):

    if request.user.is_authenticated():
        return redirect("group")

    # email = request.GET.get('email', '')

    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']
            profile_obj = UserDetails.objects.get(user__email=email)
            username = profile_obj.user.username
            user = authenticate(username=username, password=form.cleaned_data['password'])
            if user:
                if user.is_active:
                    login(request, user)

                    return redirect('main_home')

        return render(request, 'login.html', {'form':form})

    else:
        form = LoginForm(request.POST or None )
        return render(request, 'login.html', {"form":form})

@login_required
def user_logout(request):
    """
        Function is used to logout the user from the day planner.
    """

    logout(request)
    return redirect("login")

def Signup(request):
    if request.user.is_authenticated():
        return redirect('group')

    form = SignUpForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = User.objects.create_user(
                username=create_username('%s %s' % (form.cleaned_data["first_name"], form.cleaned_data["last_name"])),
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password'],
                is_active = True,
            )
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()

            UserDetail = UserDetails.objects.create(
            user=user
            )
            return redirect('login')
    else:
        form = SignUpForm()

    return render(request, "signup.html", {
        "form":form,
        })

# def details(request):
#     form = UserDetailsForm(request.POST or None)
#     return render(request, "details.html", {})

chat/accounts/templates/details.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-2">
            <h3> <strong>Register</strong> </h3>
        </div>
    </div>
<div class="row">
    <div class=" col-md-offset-2 col-md-8"><br>
        <div class="panel panel-default">
            <div class="panel-body">
                <form class='form-horizontal' data-toggle="validator" multiple method="post" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-offset-1 col-sm-3">
                                <label class="control-label" for="id_first_name">*First Name :</label>
                            </div>
                            <div class="col-sm-6">
                                {{ form.first_name }}
                                <div class="help-block with-errors"></div>
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger server_errors" role="alert">
                                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                        {{ form.first_name.errors.as_text }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-offset-1 col-sm-3">
                                <label class="control-label" for="id_last_name">*Last Name :</label>
                            </div>
                            <div class="col-sm-6">
                                {{ form.last_name }}
                                <div class="help-block with-errors"></div>
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger server_errors" role="alert">
                                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                        {{ form.last_name.errors.as_text }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-offset-1 col-sm-3">
                                <label class="control-label" for="id_email">*Email :</label>
                            </div>
                            <div class="col-sm-6">
                                {{ form.email }}
                                <!-- <div class="help-block with-errors"></div> -->
                                <!-- {% if form.email.errors %}
                                    <div class="alert alert-danger server_errors" role="alert">
                                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                        {{ form.email.errors.as_text }}
                                    </div>
                                {% endif %} -->
                                <div class="help-block with-errors "></div>
                                <small class="error-field" style="color:#c14f5f;">
                                    {% if form.non_field_errors and not form.email.errors %}
                                        {{ form.non_field_errors.as_text }}
                                    {% else %}
                                        {{ form.email.errors.as_text }}
                                    {% endif %}
                                </small>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-offset-1 col-sm-3">
                                <label class="control-label" for="id_password">*Password :</label>
                            </div>
                            <div class="col-sm-6">
                                {{ form.password }}
                                <!-- <div class="help-block with-errors"></div>
                                {% if form.password.errors %}
                                    <div class="alert alert-danger server_errors" role="alert">
                                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                        {{ form.password.errors.as_text }}
                                    </div>
                                {% endif %} -->
                                <div class="help-block with-errors "></div>
                                <small class="error-field" style="color:#c14f5f;">
                                    {% if form.non_field_errors and not form.password.errors %}
                                        {{ form.non_field_errors.as_text }}
                                    {% else %}
                                        {{ form.password.errors.as_text }}
                                    {% endif %}
                                </small>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-offset-1 col-sm-3">
                                <label class="control-label" for="id_confirm_password">*Confirm Password :</label>
                            </div>
                            <div class="col-sm-6">
                                {{ form.confirm_password }}
                                <div class="help-block with-errors"></div>
                                {% if form.confirm_password.errors %}
                                    <div class="alert alert-danger server_errors" role="alert">
                                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                        {{ form.confirm_password.errors.as_text }}
                                    </div>
                                {% endif %}
                                <!-- <small class="error-field" style="color:#c14f5f;">
                                    <div class="help-block with-errors "></div>
                                    {% if form.non_field_errors and not form.confirm_password.errors %}
                                        {{ form.non_field_errors.as_text }}
                                    {% else %}
                                        {{ form.confirm_password.errors.as_text }}
                                    {% endif %}
                                </small> -->
                            </div>
                        </div>
                    </div>

                    <div class='row'>
                        <div class="col-sm-offset-1 col-sm-3">
                             <label class="control-label"></label>
                        </div>
                        <div class="col-sm-6">
                            <div class="input-group">
                                 <input class="btn btn-primary btn-block" style="background-color: #09707c" type='submit' value='Sign Up'>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

chat/accounts/templates/login.html
{% extends 'base.html' %}
{% load chat_tags %}
{% block content %}
	<div class="breadcrumb-container">
		<div class="container">
			<ol class="breadcrumb">
				<li><i class="fa fa-home pr-10"></i><a href="index.html">Home</a></li>
				<li class="active">Login/<a href="{% url "signup" %}">Sign Up</a></li>
				<p style="float:right;"><strong>Total No. of Users {% total_users %} </strong></p>
			</ol>
		</div>
	</div>
	<div class="main-container dark-translucent-bg" style="background-image:url('images/background-img-6.jpg');">
		<div class="container">
			<div class="row">
				<div class="main object-non-visible" data-animation-effect="fadeInUpSmall" data-effect-delay="100">
					<div class="form-block center-block p-30 light-gray-bg border-clear">
						<div class="row">
							<div class="col-md-offset-5 title">
								<h2>Login / <a href="{% url "signup" %}">Sign Up</a></h2><br><br>
							</div>
							<!-- <div class="col-md-2">
								<p>Total No. of Users {% total_users %} </p>
							</div> -->
						</div>
						<form action="{% url 'login' %}" method="post" class="top_margin" data-toggle="validator" role="form">
							{% csrf_token %}
			                    <div class="form-group">
									<div class="row">
										<div class="col-md-offset-3 col-md-1">
			                        		{{ form.email.label_tag }}
										</div>
										<div class="col-md-5">
			                      			  {{ form.email }}
					                        <small class="error-field" style="color:#c14f5f;">
					                            <div class="help-block with-errors "></div>
					                            {% if form.non_field_errors and not form.email.errors %}
					                                {{ form.non_field_errors.as_text }}
					                            {% else %}
					                                {{ form.email.errors.as_text }}
					                            {% endif %}
					                        </small>
										</div>
			                  	  </div>
								</div>
		                    <div class="form-group">
								<div class="row">
									<div class="col-md-offset-3 col-md-1">
		                        		{{ form.password.label_tag }}
									</div>
									<div class="col-md-5">
			                        	{{ form.password }}
				                        <small class="error-field">
				                            <div class="help-block with-errors"></div>
											{% if form.non_field_errors and not form.password.errors %}
												{{ form.non_field_errors.as_text }}
											{% else %}
				                          		{{ form.password.errors.as_text }}
											{% endif %}
				                        </small>
									</div>
			                        {% if error_message %}
			                            <br>
			                        {% endif %}
								</div>
			                </div><br>
							<div class="form-group">
								<div class="row">
									<div class="col-md-offset-4 col-md-1">
		                        <button class="btn btn-info" type='submit'>
		                            <b>Sign in</b>
		                        </button>
									</div>
								</div>
		                    </div>
		                </form>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

chat/accounts/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-2">
            <h2> <strong style="color:#0b7c58">Sign Up</strong> </h2>
        </div>
    </div>
    <div class="row">
        <div class=" col-md-offset-2 col-md-8"><br>
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class='form-horizontal' data-toggle="validator" multiple method="post" role="form">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-offset-1 col-sm-3">
                                    <label class="control-label" for="id_first_name">*First Name :</label>
                                </div>
                                <div class="col-sm-6">
                                    {{ form.first_name }}
                                    <div class="help-block with-errors"></div>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger server_errors" role="alert">
                                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                            {{ form.first_name.errors.as_text }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-offset-1 col-sm-3">
                                    <label class="control-label" for="id_last_name">*Last Name :</label>
                                </div>
                                <div class="col-sm-6">
                                    {{ form.last_name }}
                                    <div class="help-block with-errors"></div>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger server_errors" role="alert">
                                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                            {{ form.last_name.errors.as_text }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-offset-1 col-sm-3">
                                    <label class="control-label" for="id_email">*Email :</label>
                                </div>
                                <div class="col-sm-6">
                                    {{ form.email }}
                                    <!-- <div class="help-block with-errors"></div> -->
                                    <!-- {% if form.email.errors %}
                                        <div class="alert alert-danger server_errors" role="alert">
                                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                            {{ form.email.errors.as_text }}
                                        </div>
                                    {% endif %} -->
                                    <div class="help-block with-errors "></div>
                                    <small class="error-field" style="color:#c14f5f;">
                                        {% if form.non_field_errors and not form.email.errors %}
                                            {{ form.non_field_errors.as_text }}
                                        {% else %}
                                            {{ form.email.errors.as_text }}
                                        {% endif %}
                                    </small>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-offset-1 col-sm-3">
                                    <label class="control-label" for="id_password">*Password :</label>
                                </div>
                                <div class="col-sm-6">
                                    {{ form.password }}
                                    <!-- <div class="help-block with-errors"></div>
                                    {% if form.password.errors %}
                                        <div class="alert alert-danger server_errors" role="alert">
                                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                            {{ form.password.errors.as_text }}
                                        </div>
                                    {% endif %} -->
                                    <div class="help-block with-errors "></div>
                                    <small class="error-field" style="color:#c14f5f;">
                                        {% if form.non_field_errors and not form.password.errors %}
                                            {{ form.non_field_errors.as_text }}
                                        {% else %}
                                            {{ form.password.errors.as_text }}
                                        {% endif %}
                                    </small>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-offset-1 col-sm-3">
                                    <label class="control-label" for="id_confirm_password">*Confirm Password :</label>
                                </div>
                                <div class="col-sm-6">
                                    {{ form.confirm_password }}
                                    <div class="help-block with-errors"></div>
                                    {% if form.confirm_password.errors %}
                                        <div class="alert alert-danger server_errors" role="alert">
                                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                            {{ form.confirm_password.errors.as_text }}
                                        </div>
                                    {% endif %}
                                    <!-- <small class="error-field" style="color:#c14f5f;">
                                        <div class="help-block with-errors "></div>
                                        {% if form.non_field_errors and not form.confirm_password.errors %}
                                            {{ form.non_field_errors.as_text }}
                                        {% else %}
                                            {{ form.confirm_password.errors.as_text }}
                                        {% endif %}
                                    </small> -->
                                </div>
                            </div>
                        </div>

                        <div class='row'>
                            <div class="col-sm-offset-1 col-sm-3">
                                 <label class="control-label"></label>
                            </div>
                            <div class="col-sm-6">
                                <div class="input-group">
                                     <input class="btn btn-primary btn-block" style="background-color: #09707c" type='submit' value='Sign Up'>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}