chat/chat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('chating.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^profile/', include('profiles.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {"document_root": settings.MEDIA_ROOT})
]
# if settings.DEBUG:
#     urlpatterns += url('', (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

chat/profiles/urls.py
from django.conf.urls import patterns, url

from . import views
urlpatterns = [
    # url(r'^home/$', views.home, name='home'),
    url(r'^$', views.profile, name='profile'),
    url(r'^main-home/$', views.mainhome, name='main_home'),
    url(r'^post/$', views.post, name='post'),
    url(r'^load-more-user/$', views.load_more_user, name='load_more_user'),
    url(r'^(?P<id>\d+)/$', views.friends_profile, name='friends_profile'),
    url(r'^add-friend/(?P<id>\d+)/$', views.add_friends, name='add_friend'),
    url(r'^home-load-more-user/$', views.home_load_more_user, name='home_load_more_user'),
    url(r'^searching-friend/$', views.searching_friend, name='searching_friend'),
    # url(r'^someonetyping/$', views.Someonetyping, name='someonetyping'),
    # url(r'^someone/$', views.Someone, name='someone'),
    # url(r'^group/$', views.group, name='group'),
    ]

chat/profiles/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.
class Friendship(models.Model):
    from_friend = models.ForeignKey(User, related_name="friend_set")
    to_friend = models.ForeignKey(User, related_name="to_friend_set")
    created = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return '%s, %s' %(self.from_friend.username, self.to_friend.username)
        # return '%s' %(self.to_friend.username)

class Posts(models.Model):
    user = models.ForeignKey(User)
    to_friend_wall = models.ForeignKey(User, related_name="to_friend_wall_set",
        null=True, blank=True)
    status = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='img/', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)


    def __unicode__(self):
        return '%s' %(self.status)

chat/profiles/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import RequestContext, context
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.template.loader import render_to_string

from accounts.models import ExtendGroup, UserDetails, Chats
from .models import Friendship, Posts
from .froms import UserDetailsForm, PostsForm

@login_required
def profile(request):
    user = request.user
    userdetails_obj = UserDetails.objects.get(user=request.user)
    # user_status = Posts.objects.filter(user=request.user).order_by('-created')
    user_status = Posts.objects.filter(Q(user=request.user) | Q(to_friend_wall=request.user)).order_by('-created')

    if len(user_status) > 10:
        user_status = user_status[:10]
        more = True
    else:
        more = False

    # result = User.objects.filter(username=request.user)
    result = User.objects.get(username=request.user)

    friend_set = user.friend_set.all()
    values = friend_set.values("to_friend")
    following_length = len(values)
    friends_list = []
    for i in range(0, following_length):
       for key, value in values[i].iteritems():
            friends_list.append(value)

    following = User.objects.filter(id__in=friends_list)

    to_friend_set = user.to_friend_set.all()
    values_from = to_friend_set.values("from_friend_id")
    followers_length = len(values_from)
    followers_list = []
    for i in range(0, followers_length ):
        for key, value in values_from[i].iteritems():
            followers_list.append(value)

    followers = User.objects.filter(id__in=followers_list)

    # for staff in result:
    #     groups = staff.groups.all()

    groups = result.groups.all()

    if request.method == 'POST':
        form = UserDetailsForm(request.POST or None, request.FILES, instance=userdetails_obj)

        if form.is_valid():
            cd = form.cleaned_data
            userdetail = UserDetails.objects.get(user=request.user)
            userdetail.user_description = cd["user_description"]
            userdetail.state = cd["state"]
            userdetail.city = cd["city"]
            # userdetail.city = cd["city"]
            userdetail.mobile_no = cd["mobile_no"]
            userdetail.address = cd["address"]
            # userdetail = UserDetails.objects.create(user_description=cd["user_description"],
            #     state=cd["state"], city=cd["city"], mobile_no=cd["mobile_no"], address=cd["address"],
            #     )

            #
            # candidate = form.save(commit=False)
            # candidate.contact_no = form.cleaned_data['contact_no']
            # candidate.save()

            # return redirect('show_candidate', candidate_id=candidate.id)

            if request.FILES:
                userdetail.image = request.FILES.get("image")
            userdetail.save()
            print userdetail.image
            return redirect('profile')

    else:
        form = UserDetailsForm(instance=userdetails_obj)

    return render(request, 'profile.html', {"userdetails_obj": userdetails_obj,
        "form":form, "user_status":user_status, "groups":groups,
        "following":following, "following_length":following_length,
        "followers_list":followers_list, "followers_length":followers_length,
        "followers":followers, "start":10, "more":more,
    })


def friends_profile(request, id):

    userdetails_obj = UserDetails.objects.get(id=id)
    searched_user = User.objects.get(id=id)
    # user_status = Posts.objects.filter(user_id=id,).order_by('-created')
    user_status = Posts.objects.filter(Q(user_id=id) | Q(to_friend_wall=searched_user)).order_by('-created')
    user = request.user
    # searched_user = User.objects.get(id=id)

    if len(user_status) > 10:
        user_status = user_status[:10]
        more = True
    else:
        more = False


    if user == searched_user :
        return redirect("profile")

    else:
        # user = User.objects.get(id=id)
        friend = user.friend_set.all()
        friend_values = friend.values("to_friend")
        length = len(friend_values)
        if_following = []
        for i in range(0, length):
           for key, value in friend_values[i].iteritems():
                if_following.append(value)

        friend_set = searched_user.friend_set.all()
        values = friend_set.values("to_friend")
        following_length = len(values)
        friends_list = []
        for i in range(0, following_length):
            for key, value in values[i].iteritems():
                friends_list.append(value)

        following = User.objects.filter(id__in=friends_list)

        to_friend_set = searched_user.to_friend_set.all()
        values_from = to_friend_set.values("from_friend_id")
        followers_length = len(values_from)
        followers_list = []
        for i in range(0, followers_length ):
            for key, value in values_from[i].iteritems():
                followers_list.append(value)

        followers = User.objects.filter(id__in=followers_list)

    return render(request, 'profile.html', {"userdetails_obj": userdetails_obj,
        "friend_set":friend_set, "if_following":if_following,
        "user_status":user_status, "following":following, "followers":followers,
        "following_length":following_length, "followers_length":followers_length,
        "searched_user":searched_user
        })


def add_friends(request, id):
    response = {"status": False, "errors": []}
    if request.is_ajax() and request.POST['action'] == "follow" :
        friend = get_object_or_404(User, id=id)
        friendship = Friendship( from_friend=request.user, to_friend=friend)
        friendship.save()
        response["status"] = True
        return HttpResponse(json.dumps(response))

    if request.is_ajax() and request.POST['action'] == "unfollow" :
        friend = get_object_or_404(User, id=id)
        friendship = Friendship.objects.get(from_friend=request.user, to_friend=friend)
        friendship.delete()
        response["status"] = True
        return HttpResponse(json.dumps(response))

def mainhome(request):
    result = User.objects.get(username=request.user)
    groups = result.groups.all()
    userdetails_obj = UserDetails.objects.get(user=request.user)
    user = request.user
    user_id = request.user.id
    friend_set = user.friend_set.all()
    values = friend_set.values("to_friend")
    length = len(values)
    friends_list = []
    for i in range(0, length):
       for key, value in values[i].iteritems():
            friends_list.append(value)

    friends_list.append(user_id)

    friends = User.objects.filter(id__in = friends_list)
    # post = Posts.objects.filter(Q(user_id__in = friends_list) | Q(to_friend_wall__in = friends)).order_by('-created')
    # post = Posts.objects.filter(to_friend_wall__in = friends).order_by('-created')
    post = Posts.objects.filter(user_id__in = friends_list).order_by('-created')

    if len(post) > 10:
        post = post[:10]
        more = True
    else:
        more = False

    # if request.method == 'POST':
    #     form = PostsForm(request.POST or None, request.FILES, instance=userdetails_obj)
    #
    #     if form.is_valid():
    #         cd = form.cleaned_data
    #         post = Posts.objects.get(user=user)
    #         post.status = cd["status"]
    #
    #         if request.FILES:
    #             post.image = request.FILES.get("image")
    #         post.save()
    #         print post.image

    # else:
    form = PostsForm()

    return render(request, "home_page.html", {"user":user, "post":post,
        "userdetails_obj":userdetails_obj, "groups":groups, "more":more,
        "start":10, "form":form
        })


def post(request):
    response = {"status": False, "errors": []}

    if request.is_ajax() and request.POST["for"] == "posting_on_ourself_wall":

        # if request.method == 'POST':
        #     form = PostsForm(request.POST, request.FILES)
        #     if form.is_valid():
        #         print "yes"
        #         status = form.cleaned_data["status"]
        #         print status
        #

        status = request.POST["post"]
        image = request.POST.get("image")
        print image
        post = Posts.objects.create(user=request.user, status=status, image=image)

        print post.image
                # post.status = cd["status"]


        # status = request.POST["post"]
        # post = Posts.objects.create(user=request.user, status=status)
        # post = get_object_or_404(Posts, user=request.user)
        # post.status = status
        # post.save()
        # print post.status
        response["post"] = post.status
        response["post_user_first_name"] = post.user.first_name
        response["post_user_last_name"] = post.user.last_name
        response["status"] = True
        return HttpResponse(json.dumps(response))

    if request.is_ajax() and request.POST["for"] == "posting_on_friends_wall":
        status = request.POST["post"]
        friend_id = request.POST["friend_id"]
        friend = User.objects.get(id=friend_id)
        post = Posts.objects.create(user=request.user, status=status, to_friend_wall=friend )
        # post.to_friend_wall = user.friend_id
        # post.save()
        response["post"] = post.status
        response["post_user_first_name"] = post.user.first_name
        response["post_user_last_name"] = post.user.last_name
        response["post_to_friend_wall_frist_name"] = post.to_friend_wall.first_name
        response["post_to_friend_wall_last_name"] = post.to_friend_wall.last_name
        response["post_user_id"] = post.user.id
        response["post_to_friend_wall_id"] = post.to_friend_wall.id
        response["status"] = True
        return HttpResponse(json.dumps(response))


# def posts(request):

chat/profiles/templates/home.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-offset-8 col-md-6">
            <h1>{{ user.full_name }}</h1>
        </div>
    </div>
</div>

{% endblock %}

chat/profiles/templates/home_load_more_user.html
<div class="row">
    <div class="col-md-12" id="displayed_post">
        {% for post in user_posts %}
            {% if post.to_friend_wall %}
                <a href="{% url "friends_profile" post.user.id %}" ><strong> {{ post.user.first_name }} {{ post.user.last_name }} </strong> </a>  Writes on
                <a href="{% url "friends_profile" post.to_friend_wall.id %}" > <strong> {{ post.to_friend_wall.first_name }} {{ post.to_friend_wall.last_name }} </strong> </a> Wall  <br><br>
                <!-- <input type="hidden" name="start" value="{{ start }}" id="id_pagination_start"/> -->
                <div class="well" style="background-color:#CCFF99;">
                    {{ post }}
                </div> <hr>
            {% else %}
            <a href="{% url "friends_profile" post.user.id %}" ><strong> {{ post.user.first_name }} {{ post.user.last_name }} </strong> </a><br><br>
            <div class="well" style="background-color:#CCFF99;">
                {{ post }}
            </div> <hr>
            {% endif %}
        <!-- <div class="well" style="background-color:#CCFF99;">
            {{ status }}
        </div> -->
    {% endfor %}
    </div>
</div>

chat/profiles/templates/home_page.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<!-- <div class="container">
    <div class="row">
        <div class="col-md-6">
            {% for p in post %}
            <p>{{ p }} </p>
            {% endfor %}
        </div>
    </div>
</div>

 -->
<div class="container">
    <div class="row"><br>
        <div class="col-md-3">
            {% if userdetails_obj.image %}
            <img src="{{ userdetails_obj.image.url }}" alt="{{userdetails_obj.first_name}}" width="200px" height="190px">
            {% else %}
            <img src="{% static 'img/noimagefound.jpg' %}" alt="{{userdetails_obj.first_name}}" width="190px" height="190px">
            {% endif %}
            <p><strong><h4 style="margin-left:25px;">{{ request.user.first_name }} {{ request.user.last_name }}</h4></strong></p><br>
            <div class="panel panel-default" style="background-color:#CCFF99; width:200px;">
                <div class="panel-body">
                    <center><h4>Chat Rooms</h4><br>
                    {% for group in groups %}
                        <center><button type="button" class="btn btn-success" onclick="window.location.href='{% url 'home' group.id %}'">
                        <strong style="color:white">{{ group.name }}</strong></button></center><br>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="panel panel-default" style="background-color:#CCFF99;">
                <div class="panel-body">
                    <!-- <form id="post_form" method="post" enctype='multipart/form-data'>
                        {% csrf_token %}
                        <div class="form-group" >
                            {{ form.status }} <br>
                            {{ form.image }} <br>
                            <input type="hidden" name="start" value="{{ start }}" id="id_pagination_start"/>
                            <input class="btn btn-primary" type='submit' id="status_button" value='Post'>
                        </div>
                    </form> -->

                    <form id="post_form" method="post" enctype='multipart/form-data' >
                        {% csrf_token %}
                        <div class="form-group">
                            <textarea rows="3" cols="0" class="form-control" id="id_status" placeholder="Describe yourself here..."> </textarea><br>
                            <input type="hidden" name="start" value="{{ start }}" id="id_pagination_start"/>
                            <!-- <input type="file" name="image"  id="image_post" accept="image/*"> <br> -->
                            <input class="btn btn-primary" type='submit' id="status_button" value='Post'>
                        </div>
                    </form>
                </div>
            </div><hr>
            <div  id="displayed_post">
                {% for p in post %}
                    {% if p.to_friend_wall %}
                    <a href="{% url "friends_profile" p.user.id %}"><strong>{{ p.user.first_name }} {{ p.user.last_name }}</strong></a>
                     writes on <a href="{% url "friends_profile" p.to_friend_wall.id %}" > <strong> {{ p.to_friend_wall.first_name }} {{ p.to_friend_wall.last_name }} </strong> </a> Wall <br><br>
                    <div class="well" style="background-color:#CCFF99;">
                        <p>{{ p }} </p>
                    </div>
                    <hr>
                    {% else %}
                    <a href="{% url "friends_profile" p.user.id %}"><strong>{{ p.user.first_name }} {{ p.user.last_name }}</strong></a> <br><br>
                        <div class="well" style="background-color:#CCFF99;">
                            <p>{{ p }} </p>
                        </div>
                        <hr>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="col-md-2">
        </div>
    </div>
</div>

<script>

{% if more %}
    bindEvent("{{ start }}");
{% endif %}

$(document).ready(function(){

    $('#post_form').on('submit', function(event){
        event.preventDefault();
        $.ajax({
            url : "{% url 'post' %}",
            type : 'POST',
            data : {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                post: $('#id_status').val(),
                image: $("#image_post").val(),
                for: "posting_on_ourself_wall"
                // csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
                // msgbox : $('#chat-msg').val(),
                // group_id : {{ group_obj.id }}
            },
            success: function(response){
                response = JSON.parse(response);
                if (response.status){

                    $("#displayed_post").prepend(
                        "<a><strong> "+response.post_user_first_name+ " " + response.post_user_last_name + "</strong> </a><br><br>"+
                        "<div class='well' style='background-color:#CCFF99;'>"+response.post+"</div><hr>"
                       )

                    // $("#displayed_post").prepend("{% for status in user_status %} {% if status.to_friend_wall %}"+
                    //     "<a href='{% url 'friends_profile' status.user.id %}'>"+
                    //     "<strong> {{ status.user.first_name }} {{ status.user.last_name }} </strong> </a><br><br>"+
                    //     "<div class='well' style='background-color:#CCFF99;'>"+response.post+"</div><hr>"+
                    //     "{% endif %} {% endfor %} ")


                    // $("#displayed_post").prepend("<div class='well' style='background-color:#CCFF99;'>"+response.post+"</div>")
                    $("#post_form")[0].reset();
                }

            }
        });
    });

    $('#status_button').attr('disabled','disabled');
    $('#id_status').keypress(function(){
        if($(this).val() != null ){
            $('#status_button').removeAttr('disabled');
        }
        else{
            $('#status_button').attr('disabled', 'disabled');
        }
    });
    // $('#id_image').val() == true

});
function bindEvent(start){
    $(window).scroll(function() {
        if($(window).scrollTop() + $(window).height() > $(document).height()-300){
            load_status(start);
        }
    });
}

function load_status(start) {
    $(window).unbind('scroll');
    $('#id_pagination_start').val(start);
    // $("#spin_svg").show();

    $.ajax({
        url: "{% url 'home_load_more_user' %}",
        type: "POST",
        data: $('#post_form').serialize(),
        success: function(response) {
            // $("#spin_svg").hide();
            $("#displayed_post").append(response.data);

            if (response.more){
                bindEvent(response.start);
            }
        }
    });
    return false;
}


</script>
{% endblock %}

chat/profiles/templates/load_more_user.html
<div class="row">
    <div class="col-md-12" id="displayed_post">
        {% for status in user_status %}
            {% if status.to_friend_wall %}
                <a href="{% url "friends_profile" status.user.id %}" ><strong> {{ status.user.first_name }} {{ status.user.last_name }} </strong> </a>  Writes on
                <a href="{% url "friends_profile" status.to_friend_wall.id %}" > <strong> {{ status.to_friend_wall.first_name }} {{ status.to_friend_wall.last_name }} </strong> </a> Wall  <br><br>
                <!-- <input type="hidden" name="start" value="{{ start }}" id="id_pagination_start"/> -->
                <div class="well" style="background-color:#CCFF99;">
                    {{ status }}
                </div> <hr>
            {% else %}
            <a href="{% url "friends_profile" status.user.id %}" ><strong> {{ status.user.first_name }} {{ status.user.last_name }} </strong> </a><br><br>
            <div class="well" style="background-color:#CCFF99;">
                {{ status }}
            </div> <hr>
            {% endif %}
            <!-- <div class="well" style="background-color:#CCFF99;">
                {{ status }}
            </div> -->
        {% endfor %}
    </div>
</div>